### ISSUE TITLE
user-can-delete-an-entry

### ISSUE THREAD

**Issue by JenBowman1** [JenBowman1/code-journal#2]
## 💰 Motivation

If a user decides that they no longer wish to keep an entry, they should be able to delete it.

## 📐 Plan

Allow users to delete an entry from its edit screen.

## 🖼️ Wireframes

![user can delete an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-mobile.png)
![user can delete an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-desktop.png)

## ✅ Task List
- [ ] Add a button to the entry form with the text **Delete Entry** which is only visible when an entry is currently being edited.
- [ ] Show a confirmation modal when the user clicks **Delete Entry**
- [ ] When the user clicks **Cancel**, hide the modal.
- [ ] When the user clicks **Confirm**:
  - [ ] remove the corresponding entry object from the data model's entry array.
  - [ ] remove the entry's `li` element from the DOM.
  - [ ] conditionally uses the `toggleNoEntries` function to show the no entries text if needed.
  - [ ] hide the modal.
  - [ ] swap to the Entries view.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
Example
[Here is an example in case you'd like to see it](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/code-journal/v2/user-can-delete-an-entry.gif). In the workplace, you are normally given static images to base your work on. You should primarily base your implementation on the wireframe in your GitHub Issue.

You can also sign into figma.com to see the original wireframes for the project [here](https://www.figma.com/file/Zg7KvZzySLwzZUiSe79MCP/code-journal).

Hints
You can style buttons to look like normal links.
Workflow
Be sure to stick with [the workflow](https://github.com/Learning-Fuze/code-journal-instructions#workflow) while building.
